CREATE OR REPLACE SCHEMA EXTRACT;

CREATE OR REPLACE SCHEMA STAGE;

CREATE OR REPLACE SCHEMA RAW;

CREATE OR REPLACE SCHEMA DWH;

CREATE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);